web:
    build: .
    links:
        - postgres:db
    environment:
        PGHOST: db
    ports:
        - 8001:80


postgres:
    image: postgres:9.5
    environment:
        POSTGRES_PASSWORD: postgres
